### PR TITLE
added notes

### PR DESCRIPTION
**Pull request by dmc2015**
added some notes/comments

### CODE REVIEW

**Comment by dmc2015** [comment]
after making some fixes, you could also build out user login

**Comment by dmc2015** [comment]
I think it is confusing what the difference is between a goal and a habit, from the user perspective and from a code perspective.

**Comment by dmc2015** [comment]
from the goal list, it isn't obvious that the goal titles are actually links

**Comment by dmc2015** [comment]
you could have a slide down that reveals the habits for a goal on the main page if you like/want to add some interactivity

**Comment by dmc2015** [comment]
when you check off habits from a goal they should persist, I did something similar in one of the todo apps

**Comment by dmc2015** [comment]
you could add the ability to delete a specific habit

**Comment by tishana** [comment]
Thanks, Don,

I will be working on this project over the break. Particularly with habits, I want then the stay checked, like the todo app. I also want to add users and have a user to know their progress. More than likely, I'll be asking for help with this, lol.

**Pull request closed without merging**
